version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: WebChatUser
  MYSQL_PASSWORD: WebChatMySQl
  MYSQL_DATABASE: webchat
  REACT_APP_SERVER_PORT: 8000

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./WebChat.sql:/docker-entrypoint-initdb.d/WebChat.sql
  server:
    build: ./server
    image: webchat_server
    container_name: node_server_container
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 8000:8000
    volumes:
      - ./server/routes:/app/routes
      - ./server/models:/app/models
      - ./server/controllers:/app/controllers
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    image: webchat_client
    container_name: node_client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 80:3000
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
    links:
      - server
    command: npm start

