-- MySQL Script generated by MySQL Workbench
-- Mon Mar 14 19:23:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webchat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webchat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webchat` DEFAULT CHARACTER SET utf8 ;
USE `webchat` ;

-- -----------------------------------------------------
-- Table `webchat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`users` (
  `u_id` INT NOT NULL AUTO_INCREMENT,
  `u_login` VARCHAR(50) NOT NULL,
  `u_password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`u_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webchat`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`profiles` (
  `p_id` INT NOT NULL AUTO_INCREMENT,
  `p_user_id` INT NOT NULL,
  `p_firstname` VARCHAR(50) NOT NULL,
  `p_lastname` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`p_id`),
  INDEX `fk_profiles_users_idx` (`p_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_users`
    FOREIGN KEY (`p_user_id`)
    REFERENCES `webchat`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webchat`.`tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`tokens` (
  `t_id` INT NOT NULL AUTO_INCREMENT,
  `t_user_id` INT NOT NULL,
  `t_token` VARCHAR(100) NOT NULL,
  `t_create_at` DATETIME NOT NULL,
  PRIMARY KEY (`t_id`),
  INDEX `fk_tokens_users1_idx` (`t_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tokens_users1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `webchat`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webchat`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`rooms` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `r_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`r_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webchat`.`users_m2m_rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webchat`.`users_m2m_rooms` (
  `ur_id` INT NOT NULL AUTO_INCREMENT,
  `ur_user` INT NOT NULL,
  `ur_room` INT NOT NULL,
  PRIMARY KEY (`ur_id`),
  INDEX `fk_users_m2m_rooms_rooms1_idx` (`ur_room` ASC) VISIBLE,
  INDEX `fk_users_m2m_rooms_users1_idx` (`ur_user` ASC) VISIBLE,
  CONSTRAINT `fk_users_m2m_rooms_rooms1`
    FOREIGN KEY (`ur_room`)
    REFERENCES `webchat`.`rooms` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_m2m_rooms_users1`
    FOREIGN KEY (`ur_user`)
    REFERENCES `webchat`.`users` (`u_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
